name: taskly
description: A new Flutter project.

publish_to: "none"

version: 1.1.3+3

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bubble_bottom_bar: ^2.0.0
  cupertino_icons: ^1.0.4
  date_format: ^2.0.6
  flutter_local_notifications: ^9.5.3+1
  flutter_native_timezone: ^2.0.0
  flutter_slidable: ^1.3.0
  flutter_svg: ^1.1.0
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  hive: ^2.2.1
  intl: ^0.17.0
  lottie: ^1.3.0
  path_provider: ^2.0.10
  timezone: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lottie/
    - assets/images/
